### ISSUE TITLE
Handling several slots in the same sentence

### ISSUE THREAD

**Issue by Asma-droid** [SimGus/Chatette#34] opened 2019-12-19 10:41 UTC
Hi all,

Thanks to this great library :-)

I would like to use several slots within a same sentence but the produced json file does not pick up the right start and end of the slots.

Below a simple example:

******** txt_file ***********
%[&ask_toilet](3)
    where the @[toilet#singular] is @[please]?

@[toilet#singular]
    toilet
    loo
@[please]
    please
    plz

***** json result ***********

{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "entities": [
          {
            "end": 13,
            "entity": "toilet",
            "start": 10,
            "value": "loo"
          },
          {
            "end": 42,
            "entity": "please",
            "start": 36,
            "value": "please"
          }
        ],
        "intent": "ask_toilet",
        "text": "Where the loo is please?"
      },
      {
        "entities": [
          {
            "end": 13,
            "entity": "toilet",
            "start": 10,
            "value": "loo"
          },
          {
            "end": 39,
            "entity": "please",
            "start": 36,
            "value": "plz"
          }
        ],
        "intent": "ask_toilet",
        "text": "where the loo is plz?"
      },
      {
        "entities": [
          {
            "end": 16,
            "entity": "toilet",
            "start": 10,
            "value": "toilet"
          },
          {
            "end": 39,
            "entity": "please",
            "start": 36,
            "value": "plz"
          }
        ],
        "intent": "ask_toilet",
        "text": "where the toilet is plz?"
      }
    ],
    "entity_synonyms": [],
    "lookup_tables": [],
    "regex_features": []
  }
}

Any idea please ???

**Comment by SimGus** [comment] 2019-12-19 21:07
Hi,

What you report seems related to [issue #22](https://github.com/SimGus/Chatette/issues/22) which was fixed in v1.6.1.
Using the template you provided, I cannot reproduce the results you get.

Would you mind giving a little more information about the environment you run chatette in? Namely, I'd need to know:
- What version of Chatette are you running? You can find that by running `python -m chatette --version`.
- Which version of python do you use?
- What OS are you running?

Thanks in advance :)

**Comment by Asma-droid** [comment] 2019-12-30 19:58
Thanks a lot.  It works fine!! I have just one other problème. I use the french language however the actual code does not support UTF8 encoding. Any help please!!!

**Comment by SimGus** [comment] 2019-12-30 21:48
Your welcome!

For Unicode encoding, I guess you are running Windows, which is likely to encode your files using Windows-1252 encoding. Try using a file editor that allows you to save your template files in UTF-8 and feeding them to Chatette should work without a problem.
Using a recent version of python (>= 3.5 I would say) could also help.

Just so you know, I speak French and I have no problem running Chatette to produce French datasets by running Linux (whatever the Python version) and encoding all my files in UTF-8.

Hope this helps! Feel free to ask if you need help again!

**Comment by Asma-droid** [comment] 2020-01-05 11:02
Thanks a lot. It works fine for me.

Just another question. How to avoid redendency. In fact, if i put 100 as the augmentation parameter, the algorithm generate redandant sentences.

**Comment by SimGus** [comment] 2020-01-05 17:56
What exactly do you mean by "redundancy"? The generated data should never contain duplicates, so if you get the same generated sentence twice (or more times), this is a bug.

If you mean your sentences are too close to each other, this simply depends on your templates. A good way to have variation in the generated sentences is to have a lot of rules in your aliases, slots and templates.
You can take a look at [different examples](https://github.com/SimGus/Chatette/tree/master/examples) on the repo if you want to see how to make good templates.

Cheers!

**Comment by Asma-droid** [comment] 2020-01-08 13:33
Hello @SimGus 

I am so sory for my late response.

I have tried to use the simple example of the directory toilets and i have set the number of generated sentences to 1000 instead of 3. The algorithme generate duplicated. Have you a solution to avoid that ??

![image](https://user-images.githubusercontent.com/55100050/71981944-c810a680-3223-11ea-9b8c-d483bd0eee19.png)

**Comment by SimGus** [comment] 2020-01-08 18:02
Hey @Asma-droid,

The two sentences are actually not duplicates: one of them starts with an uppercase letter, while the other one starts with a lowercase letter.
If you want to avoid generating sentences with different cases, simply remove the ampersand `&` that are at the beginning of the unit declaration (so for the toilet example, remove the ampersand in `%[&ask_toilet](100)`).

I hope this helps.

**Comment by Asma-droid** [comment] 2020-01-09 12:21
Thank you  for this response !

**Comment by SimGus** [comment] 2020-01-09 20:28
You're welcome! I will close this issue as it seems fixed.

**Closed by SimGus** 2020-01-09 20:28 UTC
Labels: question
