### ISSUE TITLE
error in markdown file generation

### ISSUE THREAD

**Issue by naikshubham** [SimGus/Chatette#43] opened 2020-04-16 18:48 UTC
I encountered error while generating markdown file 

master chatette file is as below:
------------------------------------------------
%[test_intent]
	~[for] @[entity_name_1] ~[for]
	
|alias_and_entity.chatette
-------------------------------------------------

alias_and_entity chatette file is as below:
---------------------------------------------
@[entity_name_1]
	~[names]
	
~[names]
	test names containing 4 words
	test name having 5 unique words
	cashflows and investment work

~[for]
	for 
	on 
	to
----------------------------------------

Command used for output generation 
python -m chatette new_chatette.chatette -a rasa-md

Output is as below:
----------------------------------------------
## intent:test_intent
- for cash [ flows and investment work for ] (entity_name_1)
- for cash [ flows and investment work on ] (entity_name_1)
- for cash [ flows and investment work to ] (entity_name_1)
- for test [ name having 5 unique words for ] (entity_name_1)
- for test [ name having 5 unique words on ] (entity_name_1)
- for test [ name having 5 unique words to ] (entity_name_1)
- for test [ names containing 4 words for ] (entity_name_1)
- for test [ names containing 4 words on ] (entity_name_1)
- for test [ names containing 4 words to ] (entity_name_1)
- on cashf [ lows and investment work for ] (entity_name_1)
- on cashf [ lows and investment work on ] (entity_name_1)
- on cashf [ lows and investment work to ] (entity_name_1)
- on test  [ name having 5 unique words for ] (entity_name_1)
- on test  [ name having 5 unique words on ] (entity_name_1)
- on test  [ name having 5 unique words to ] (entity_name_1)
- on test  [ names containing 4 words for ] (entity_name_1)
- on test  [ names containing 4 words on ] (entity_name_1)
- on test  [ names containing 4 words to ] (entity_name_1)
- to cashf [ lows and investment work for ] (entity_name_1)
- to cashf [ lows and investment work on ] (entity_name_1)
- to cashf [ lows and investment work to ] (entity_name_1)
- to test  [ name having 5 unique words for ] (entity_name_1)
- to test  [ name having 5 unique words on ] (entity_name_1)
- to test [ name having 5 unique words to ] (entity_name_1)
- to test [ names containing 4 words for ] (entity_name_1)
- to test  [ names containing 4 words on ] (entity_name_1)
- to test [ names containing 4 words to ] (entity_name_1)
-------------------------------------------------------------

Note that the entities are going outside the square brackets. @SimGus  please suggest.

**Comment by SimGus** [comment] 2020-04-17 22:14
Hi!
Thanks for this very clear bug report.

I can't seem to reproduce the issue, using Python 3.6.19 and Chatette 1.6.2 under Linux.
As I know you are using Windows 10, I'll check if I can reproduce this under a Windows system as soon as possible.

In the meantime, I hope this isn't too much of a blocking issue for you.

**Comment by SimGus** [comment] 2020-04-18 12:43
Hello!

I just tested this using a Windows 10 system to have a similar environment than what you use, but I still cannot reproduce this.

I would draw the same conclusions than I drew in issue #42.
I'd thus ask you the same thing as I did for this issue:
- Would you mind creating a [pastebin](https://pastebin.com/) for each file you used to trigger this bug?
- I'd suggest you reinstall Chatette, and if the bug still occurs, you might want to reinstall Python altogether.

I hope this will help you!

**Comment by SimGus** [comment] 2020-05-30 20:04
As for the other issue you opened, since I have no answer from your part and I can't reproduce it, I'll close this for now.

Feel free to reopen it if the problem remains!

**Closed by SimGus** 2020-05-30 20:04 UTC
Labels: bug, can't reproduce, needs clarifications
