### ISSUE TITLE
entity output in markdown file not in proper format

### ISSUE THREAD

**Issue by naikshubham** [SimGus/Chatette#42] opened 2020-04-16 06:46 UTC
If we have chatito file as below

%[duplicate]
        duplicate my @[date]

@[date]
    ~[last week]
    ~[week]

~[week]
    current week
    week

~[last week]
    last week
    prior week
    previous week

The markdown file output is as follows

## intent:duplicate
- duplicate my current week [] (date)
- duplicate my last week [] (date)
- duplicate my previous week [] (date)

However, I think the output should be as follows

## intent:duplicate
- duplicate my [ current week ] (date)
- duplicate my [ last week ] (date)
- duplicate my [ previous week ] (date)

@SimGus , please check on this and let me know the correct behavior. Thanks!

**Comment by naikshubham** [comment] 2020-04-16 09:04
It works fine with .chatette template files. Looks problem with .chatito template files.

**Comment by SimGus** [comment] 2020-04-16 18:43
Hi!

You're right, given the template you provide (albeit well indented), the exact output when using the `rasa-md` adapter should be:
```md
<!-- Generated using Chatette v1.6.2 -->

## intent:duplicate
- duplicate my [current week](date)
- duplicate my [last week](date)
- duplicate my [previous week](date)
- duplicate my [prior week](date)
- duplicate my [week](date)

```

That being said, I am unable to reproduce the behavior you describe: pasting the template you provide in both a `.chatette` and `.chatito` file, Chatette always outputs the markdown I showed above. I tested this both using Python 2.7.17 and 3.6.9.

Could you kindly provide the following information:
- Which operating system you're running
- Which version of Python you're using
- Whether you installed Chatette from PyPI or by cloning this repo
- If there's anything particular about the way you are executing Chatette

Also, can you please check there isn't any difference between both template files (the `.chatette` and `.chatito` one)?

Thanks for reporting this anyhow :)

**Comment by naikshubham** [comment] 2020-04-16 18:59
Which operating system you're running
- Windows 10

Which version of Python you're using
- Python 3.6

Whether you installed Chatette from PyPI or by cloning this repo
- from Pypi

If there's anything particular about the way you are executing Chatette
- python -m chatette filename -a rasa-md

Also, can you please check there isn't any difference between both template files (the .chatette and .chatito one)?
- The difference is that in .chatito file we don't maintain separte file and alias and entities, they are defined in the same file
- In chatette we main a separate file for alias and entities.

**Comment by SimGus** [comment] 2020-04-17 22:05
Thanks for providing this information!
However I still can't reproduce the behavior you described. I tested this using the same version of python and chatette that you use, but I'm running Linux. I will test this under Windows as soon as I can.

Can you confirm that your files are similar to those?

### Chatito files
##### file.chatito
```
%[duplicate]
    duplicate my @[date]

@[date]
    ~[last week]
    ~[week]

~[week]
    current week
    week
~[last week]
    last week
    prior week
    previous week

```

### Chatette files
##### master.chatette
```
%[duplicate]
    duplicate my @[date]

|alias-and-entity.chatette

```

##### alias-and-entity.chatette
```
@[date]
    ~[last week]
    ~[week]

~[week]
    current week
    week
~[last week]
    last week
    prior week
    previous week

```

**Comment by SimGus** [comment] 2020-04-18 12:19
Hello again!

I just tested this we the files I printed in my previous message, using a Windows 10 system. I still cannot reproduce your issue.

I assume one of 2 things must be happening on your side:
- There may be a difference between the template files you use and the ones I tried to reproduce this bug with
- There is something peculiar with your working environment (uncommon python interpreter, old chatette version,...)

Could you please create a [pastebin](https://pastebin.com/) for each of the files you use to trigger this bug, so that I can try to reproduce it with the exact same files you use?

I'd also suggest you uninstall and reinstall Chatette. If the problem still occurs after that, you could reinstall Python altogether.

I hope this helps!

**Comment by SimGus** [comment] 2020-05-30 20:02
As there as not been any answer from your part and I can't reproduce this issue, I'll close it for now.

Feel free to reopen if you can give me more information!

**Closed by SimGus** 2020-05-30 20:02 UTC
Labels: bug, can't reproduce, needs clarifications
